DELETE FROM ADMINISTRATOR WHERE 1 = 1;
INSERT INTO ADMINISTRATOR (ADMIN_NAME, ADMIN_OPENID) VALUES ('»Æ×Ïºè', 'o9P4b5M8wn6HRc9K_R34fhFLwA_o'); 
INSERT INTO ADMINISTRATOR (ADMIN_NAME, ADMIN_OPENID) VALUES ('ÊíÌõ', 'o9P4b5P0wb1-KLpuFn0qixZINE6Q'); 
INSERT INTO ADMINISTRATOR (ADMIN_NAME, ADMIN_OPENID) VALUES ('ÃÅ»¢', 'o9P4b5CcgFHTMNr5DxRfnibP-WIM'); 
INSERT INTO ADMINISTRATOR (ADMIN_NAME, ADMIN_OPENID) VALUES ('ÏÍ´¿', 'o9P4b5Ke4E6joTwWcFgTd0lzFZxA'); 
