DELETE FROM CATEGORY WHERE 1 = 1;
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES ('C00000001', '面包饼干'); 
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES ('C00000002', '方便食品'); 
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES ('C00000003', '休闲零食'); 
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES ('C00000004', '奶品饮料'); 
