DELETE FROM SERIAL WHERE 1 = 1;
INSERT INTO SERIAL (SERIAL_ID, LAST_VAL, REMARK) VALUES ('CUSTOMER_ID', 'C00000000', ' '); 
INSERT INTO SERIAL (SERIAL_ID, LAST_VAL, REMARK) VALUES ('GOOD_ID', 'G00000000', ' '); 
INSERT INTO SERIAL (SERIAL_ID, LAST_VAL, REMARK) VALUES ('ADDRESS_ID', 'A00000000', ' '); 
INSERT INTO SERIAL (SERIAL_ID, LAST_VAL, REMARK) VALUES ('ORDER_ID', 'O00000000', ' '); 
